id: IEF6C0409
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:37:18+00:00'
last_modified: '2022-06-08T06:56:22.787966+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC384
  title: 'ཀུན་རིག་དང་ཕག་མོ་བདེ་མཆོག་བཅས་ཀྱི་ཟིན་བྲིས། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    31C7:
      image_group_id: I2PD18235
      title: ''
      total_pages: 278
      order: 1
      base_file: 31C7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
