id: P006799
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1AC384
  title: 'ཀུན་རིག་དང་ཕག་མོ་བདེ་མཆོག་བཅས་ཀྱི་ཟིན་བྲིས། '
  author: ''
  volumes:
    388bc3e717f741409ca7ed04a8ba0caf:
      image_group_id: I2PD18235
      title: ''
      volume_number: 1
      total_pages: 278
      base_file: v001.txt
